services:
  opcua_server:
    build:
        dockerfile: Dockerfile
    container_name: opc_data_generator
    restart: on-failure
    ports:
      - "4840:4840"
    networks:
      opc_network:
        ipv4_address: 10.116.0.2

  jupyter:
    image: jupyter/minimal-notebook
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    container_name: jupyter_notebook
    networks:
      opc_network:
        ipv4_address: 10.116.0.3

networks:
  opc_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.116.0.0/16